[changelog]
body = """

## [{{ version | trim_start_matches(pat="v") }}]{%- if release_link -%}({{ release_link }}){% endif %}
_{{ timestamp | date(format="%d %B %Y") }}_
{% for group, commits in commits | group_by(attribute="group") -%}
{%- if group != "chore" %}
### {{ group | upper_first }}

{% for commit in commits -%}
{%- if commit.scope and commit.scope != package -%}
* *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{% else -%}
* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}
{% endif -%}
{%- endfor %}

{%- endif %}

{%- endfor -%}
"""
header = """# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""

commit_parsers = [
  { message = "^feat", group = "added" },
  { message = "^changed", group = "changed" },
  { message = "^deprecated", group = "deprecated" },
  { message = "^fix", group = "fixed" },
  { message = "^security", group = "security" },
  { message = "^chore", group = "chore" },
  { message = "^update", group = "updated dependencies" },
  { message = "^doc", group = "documented" },
  { message = "^.*", group = "other" },
]

[workspace]
dependencies_update = true
features_always_increment_minor = false
pr_labels = ["release"]
release_always = false
release_commits = "^(feat|fix|docs|perf|refactor|revert|test|update)[(:]"
